import pandas as pd 
df=pd.read_csv("data.csv")
df=df.drop(columns=["No"])
df=df.dropna(subset=["Type2"])
df=df.fillna({"Type2":"None"})
df["Type"]=df["Type1"].replace({"Grass":"GRASS"})
df["Name"]=df['Name'].str.lower()
df["Legendary"]=df["Legendary"].astype(bool)
df=df.drop_duplicates()
print(df)